### ISSUE TITLE
升级k8s 1.24.0时，发现coredns镜像同步不全

### ISSUE THREAD

**Issue by changsongyang** [zhangguanzhang/google_containers#9]
升级k8s 1.24.0时发现k8s.gcr.io上的coredns版本过旧，发现没有同步coredns/coredns目录下新版本的镜像

**Comment by zhangguanzhang** [comment]
coredns的kubeadm里是单独的hub仓库的，只能写repo，
```yaml
dns: # https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2#DNS
  type: CoreDNS # or kube-dns
  imageRepository: docker.io 
# azk8s.cn已失效,此处使用上面的ns下镜像，使用dockerhub上coredns官方镜像，下面的images list如果显示不对，这里改成docker.io/coredns再试试
  imageTag: 1.8.4
```
如果无法拉取到官方的，kubeadm写阿里的repo的话，必须是`registry.aliyuncs.com`，代码里就是寻找 `registry.aliyuncs.com/coredns/coredns:xxx` 了

也就是上面的 `imageRepository: registry.aliyuncs.com/k8sxio` 最终的镜像会是 `registry.aliyuncs.com//k8sxio/coredns/coredns:xxx`了，阿里仓库的这种层级是不支持（现象就是你推送上去了，但是无法拉取）
